### ISSUE TITLE
ValidatingAdvancedHTMLParser fails on embedded SVG files

### ISSUE THREAD

**Issue by rmnl** [kata198/AdvancedHTMLParser#9]
It seems that the attribute-name validation that was added in version 8.1.5 causes the `ValidatingAdvancedHTMLParser` to fail when it needs to validate HTML that includes embedded `svg` files.

Take e.g.:

```python
import AdvancedHTMLParser

html = """
<div>
  <svg
    width="100%"
    height="100%"
    viewBox="0 0 100 100"
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xml:space="preserve"
    style="fill-rule:evenodd;clip-rule:evenodd;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:1.5;"
  >
    <circle
      cx="50"
      cy="50"
      r="45"
      style="fill:#ff2711;stroke:#1f9f00;stroke-width:6px;"
    />
  </svg>
</div>
"""

parser = AdvancedHTMLParser.ValidatingAdvancedHTMLParser()
parser.parseStr(html)
```

Running the above with AdvancedHTMLParser 8.1.4 returns no errors, but with 8.1.5 and above it will return:

```bash
AdvancedHTMLParser.exceptions.InvalidAttributeNameException: Parsed a tag svg  which contains an invalid attribute, 'xmlns:xlink' = 'http://www.w3.org/1999/xlink' . ( Maybe characters outside quotes in tag? )
```

In more advanced SVG files the `xlink` can cause more errors, e.g. when used with a mask, e.g.:

```html
<mask id="mask-2" fill="white" ><use xlink:href="#path-1" ></use></mask>
```

For now I can downgrade to a lower version, but that's not the best way forward. Can there be a way to except these errors for embedded SVG files?

**Comment by kata198** [comment]
So this one is a little tricky... the reason it is throwing those errors is because the colon character is NOT valid within an attribute name in an HTML5 document.

There IS a section of HTML5 for foreign namespaces (SVG, MathML), but per spec this requires changing the content-type from "text/html" to something else (such as image/svg+xml), as colon and dot are not valid within the HTML5 namespace.

So SVG2 + HTML5 works without the colon foreign namespacing, and in-fact requires it pending a different doctype and content-type.

For reference, consider Mozilla's official documentation: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

All of these names which contain the colon have been removed, and the latest standards provide you use the final name (for example just "href" instead of "xlink:href", or just "xmlns" (xmlns:link is no longer needed).

So, I would say that AdvancedHTMLParser is already doing the right thing, you're just feeding it invalid attribute names. Try finding the modern / SVG2 equivalents and using them, instead.

If you can provide me an example which actually requires a colon in the attribute name to work properly, and is valid within the HTML namespace, I will reconsider. I've not been able to find or create any, myself.

I've found reference that every major browser actually disregards the "version" attribute as well, and just uses the latest unified standard with deprecated fallback for the old forms, such as using the XML names within an HTML document.

So again, in your above example, I am able to fix it just by removing the deprecated forms of names and using the non-deprecated. Rendering provides the exact same output:

```
<div>
  <svg
    width="100%"
    height="100%"
    viewBox="0 0 100 100"
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    style="fill-rule:evenodd;clip-rule:evenodd;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:1.5;"
  >
    <circle
      cx="50"
      cy="50"
      r="45"
      style="fill:#ff2711;stroke:#1f9f00;stroke-width:6px;"
    />
  </svg>
</div>
```

Again, if you can provide me an example where using the deprecated names achieves something that the modern names cannot, I will reconsider, but as it appears ValidatingAdvancedHTMLParser is doing the right thing -- alerting when the names used fail validation. Due to "best-effort" of the other parsers, it will also skip those names when parsing. 

So try without the colon, just use last part, and that should fix the issue for you and be compliant to the latest standards.

Thanks!

**Comment by kata198** [comment]
Closing due to no reply from the OP, I am assuming you have resolved the issue per my response.

Please open another ticket if you feel this is not resolved as a user error, and requires a change to the library.

Thanks!
